version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    schedule:
      day: saturday
      interval: weekly

  # Major
  - package-ecosystem: nuget
    directory: /
    groups:
      major-updates:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
    open-pull-requests-limit: 5
    schedule:
      interval: daily

  # Minor
  - package-ecosystem: nuget
    directory: /
    groups:
      minor-updates:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-patch
    open-pull-requests-limit: 5
    schedule:
      interval: daily

  # Patch
  - package-ecosystem: nuget
    directory: /
    groups:
      patch-updates:
        patterns:
          - "*"
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    open-pull-requests-limit: 5
    schedule:
      interval: daily
