version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 5
    schedule:
      day: saturday
      interval: weekly

  # ./Directory.Build.props
  - package-ecosystem: nuget
    directory: /
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    groups:
      root-nuget-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

  # ./OpenRA.Game/OpenRA.Game.csproj
  - package-ecosystem: nuget
    directory: /OpenRA.Game
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    groups:
      open_ra.game-nuget-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

    # ./OpenRA.Mods.Common/OpenRA.Mods.Common.csproj
  - package-ecosystem: nuget
    directory: /OpenRA.Mods.Common
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    groups:
      open_ra.mods.common-nuget-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

    # ./OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj
  - package-ecosystem: nuget
    directory: /OpenRA.Platforms.Default
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    groups:
      open_ra.platforms.default-nuget-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

    # ./OpenRA.Test/OpenRA.Test.csproj
  - package-ecosystem: nuget
    directory: /OpenRA.Test
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    groups:
      open_ra.test-nuget-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major

    # ./OpenRA.WindowsLauncher/OpenRA.WindowsLauncher.csproj
  - package-ecosystem: nuget
    directory: /OpenRA.WindowsLauncher
    open-pull-requests-limit: 5
    schedule:
      interval: daily
    groups:
      open_ra.windows_launcher-nuget-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
